### ISSUE TITLE
Incorporate change for ensemble kernel from commit 3e7a968eb1b3777606ffd876fbef9acb148df481

### ISSUE THREAD

**Issue by jereliu** [statmlhb/CVEK#20]
During PR #19 , some changes in `R/interface.R` from commit 3e7a968eb1b3777606ffd876fbef9acb148df481 was not completely merged. Will incorporate these changes manually later.

**Comment by IrisTeng** [comment]
okie~

**Comment by jereliu** [comment]
Solved by #21
